"""add profile_picture column

Revision ID: c84942b94506
Revises: 
Create Date: 2025-05-21 21:35:38.152521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84942b94506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user_account', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_account', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'updated_at')
    op.drop_column('user_account', 'created_at')
    op.drop_column('user_account', 'country')
    op.drop_column('user_account', 'city')
    op.drop_column('user_account', 'address')
    op.drop_column('user_account', 'bio')
    op.drop_column('user_account', 'profile_picture')
    # ### end Alembic commands ###
